name: Repositery Download

on:
  push:

jobs:
  checkout-job:
    runs-on: ubuntu-latest


    steps:
      - name: checkout Repositery
        uses: actions/checkout@v4

      - name: Show Current Repositery
        run: pwd

      - name: List Repositery Files
        run: ls -la 