name: Multiple Commands

on:
  push:

jobs:
  linux-commands:
    runs-on: ubuntu-latest

    steps:
      - name: run linux Commands
        run: |
          echo "Hello github actions"
          date
          pwd 
          ls
