name: My First GitHub Workflow

on:
  push:

jobs:
  hello-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello GitHub Actions"

name: Multiple Commands

on:
  push:

jobs:
  linux Commands:
    runs-on: ubuntu-latest

    steps:
      - name: run linux Commands
        run: |
          echo "Hello github actions"
          date
          pwd 
          ls
